spring.application.name=todolist
spring.datasource.url=jdbc:h2:file:./data/todolist;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

app.cors.allowed-origin=https://todo-frontend-eseph7gfasa6f0gz.centralus-01.azurewebsites.net/

spring.jpa.hibernate.ddl-auto=update

server.port=8082

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1

spring.security.dev-bearer=dev-secret-token